// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjh6IFjz9ReVIJH-ZoVXOPeD_fzLt4lko',
    appId: '1:784258236937:web:9d7beb61c62b3657e86ed8',
    messagingSenderId: '784258236937',
    projectId: 'value-cleaning-95556',
    authDomain: 'value-cleaning-95556.firebaseapp.com',
    storageBucket: 'value-cleaning-95556.appspot.com',
    measurementId: 'G-4MMTNSRZCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DaK3yBu_OzghRwKSFf-l1Y32uH_o_pQ',
    appId: '1:784258236937:android:1ac81f8a676d92c7e86ed8',
    messagingSenderId: '784258236937',
    projectId: 'value-cleaning-95556',
    storageBucket: 'value-cleaning-95556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK2TIuyGw2kIht8A5DMkMgM1eJyct_PL4',
    appId: '1:784258236937:ios:bcb768ded11d43bfe86ed8',
    messagingSenderId: '784258236937',
    projectId: 'value-cleaning-95556',
    storageBucket: 'value-cleaning-95556.appspot.com',
    androidClientId: '784258236937-6gs0q3gg21kc13i7a078gtjbepan0mhh.apps.googleusercontent.com',
    iosClientId: '784258236937-ij83t5r8r6ig5lbmpqvsvpldmtilm1s9.apps.googleusercontent.com',
    iosBundleId: 'com.drcode.vc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK2TIuyGw2kIht8A5DMkMgM1eJyct_PL4',
    appId: '1:784258236937:ios:c2b8b54ec271885de86ed8',
    messagingSenderId: '784258236937',
    projectId: 'value-cleaning-95556',
    storageBucket: 'value-cleaning-95556.appspot.com',
    androidClientId: '784258236937-6gs0q3gg21kc13i7a078gtjbepan0mhh.apps.googleusercontent.com',
    iosClientId: '784258236937-qrin3ig4obu4bbtgruapj5j31nuk03oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.vc',
  );
}
